name: mobile health tech
favicon: null
layout_spectrum: 0.40262832399457693
typography_spectrum: 0.2119344500824809
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6967530706897378
  lightness: 0.7138429242186248
  saturation: 0.1317313143517822
  rhythmicContrast: 0.28535808622837067
purpose: []
