name: mobile health tech
favicon: null
layout_spectrum: 0.40262832399457693
typography_spectrum: 0.2119344500824809
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#96c4f8'
    - '#7b92b1'
    - '#566a82'
    - '#35445b'
    - '#0d1f2d'
  brandStrength: 0.6967530706897378
  lightness: 0.7138429242186248
  saturation: 0.1875
  rhythmicContrast: 0.28535808622837067
purpose: []
